/* ═══════════════════════════════════════════════
   DATA
═══════════════════════════════════════════════ */
const notifications = [
  "🔔 UPSC Civil Services 2025 Notification Released — Apply by April 30 |",
  "🔔 SSC CGL 2025 Exam Dates Announced — Tier I: July 2025 |",
  "🔔 RRB NTPC 2025 Registration Open — Last Date May 15 |",
  "🔔 AP APPSC Group 1 2025 Notification Out |",
  "🔔 Telangana TSPSC AEE 2025 Results Declared |",
  "🔔 UP Police Constable 2025 Exam Schedule Released |",
  "🔔 IBPS PO 2025 Notification Expected June 2025 |",
  "🔔 TN TRB PG Asst 2025 Counselling Ongoing |",
  "🔔 Maharashtra MPSC State Service 2025 Prelims in August |",
  "🔔 Kerala PSC LDC 2025 — Rank List Published |"
];

const categories = [
  {id:'all',icon:'🏛️',label:'All Exams'},
  {id:'central',icon:'🇮🇳',label:'Central'},
  {id:'upsc',icon:'👔',label:'UPSC'},
  {id:'railway',icon:'🚂',label:'Railways'},
  {id:'banking',icon:'🏦',label:'Banking'},
  {id:'police',icon:'👮',label:'Police'},
  {id:'teacher',icon:'📚',label:'Teaching'},
  {id:'defence',icon:'⚔️',label:'Defence'},
  {id:'state',icon:'🗺️',label:'State PSC'},
  {id:'group',icon:'📋',label:'Group D/C/B'},
  {id:'engineering',icon:'⚙️',label:'Engineering'},
  {id:'medical',icon:'🏥',label:'Medical'},
  {id:'revenue',icon:'📊',label:'Revenue'},
  {id:'judicial',icon:'⚖️',label:'Judicial'},
  {id:'agriculture',icon:'🌾',label:'Agriculture'},
  {id:'forest',icon:'🌲',label:'Forest'},
];

const EXAMS = [
  // ─── CENTRAL ───
  {
    id:'upsc_cse',title:'UPSC Civil Services (IAS/IPS/IFS)',
    short:'UPSC CSE',icon:'👔',state:'Central',type:'central',
    category:['upsc','central'],
    colorBg:'rgba(236,72,153,.15)',colorText:'#f472b6',
    conducting:'Union Public Service Commission',
    posts:'IAS, IPS, IFS, IRS and 24 other services',
    vacancies:'~1000 (varies annually)',
    eligibility:'Any Graduate (Min 21, Max 32 yrs)',
    mode:'Offline (OMR + Descriptive)',
    language:'English & Hindi',
    status:'upcoming',
    notification:'Feb 2025',
    applyLast:'March 2025',
    prelims:'June 2025',
    mains:'Sept 2025',
    interview:'Jan 2026',
    result:'April 2026',
    admitCardUrl:'https://upsc.gov.in/',
    syllabus:{
      'GS Paper I':['Indian Heritage & Culture','History of India','Geography of India & World'],
      'GS Paper II':['Governance & Constitution','Polity','Social Justice','International Relations'],
      'GS Paper III':['Technology','Economic Development','Biodiversity','Security','Disaster Management'],
      'GS Paper IV':['Ethics, Integrity & Aptitude','Public Administration'],
      'CSAT (Qualifying)':['Comprehension','Logical Reasoning','Analytical Ability','Decision Making','Basic Numeracy'],
      'Optional Subjects':['26 Options Available','Mains Paper VI & VII','250 Marks Each'],
    },
    pattern:[
      {stage:'Prelims (Screening)',papers:'GS Paper I (100Q, 200M) + CSAT (80Q, 200M)',duration:'2 hrs each',marks:'200+200'},
      {stage:'Mains (Written)',papers:'9 Papers: Essay + GS I-IV + Optional I-II + Lang',duration:'3 hrs each',marks:'1750'},
      {stage:'Personality Test',papers:'Interview by UPSC Board',duration:'~30 min',marks:'275'},
    ],
    cutoffs:[
      {year:'2023',general:'1009 (GS+Interview combined)',obc:'994',sc:'981',st:'958',ews:'984'},
      {year:'2022',general:'1011',obc:'999',sc:'988',st:'960',ews:'987'},
      {year:'2021',general:'987',obc:'975',sc:'962',st:'935',ews:'968'},
    ],
    materials:[
      {icon:'📖',title:'NCERT Books (VI–XII)',type:'Free PDFs','desc':'Foundation reading'},
      {icon:'📰',title:'The Hindu / PIB',type:'Daily','desc':'Current Affairs'},
      {icon:'📋',title:'Previous Year Papers',type:'PDF','desc':'2010–2024'},
      {icon:'🎥',title:'UPSC Pathshala YouTube',type:'Free','desc':'Video lectures'},
      {icon:'📘',title:'Laxmikant Polity',type:'Book','desc':'M.Laxmikant'},
      {icon:'📙',title:'Spectrum Modern India',type:'Book','desc':'Rajiv Ahir'},
    ],
  },
  {
    id:'ssc_cgl',title:'SSC Combined Graduate Level (CGL)',
    short:'SSC CGL',icon:'📋',state:'Central',type:'central',
    category:['central','group'],
    colorBg:'rgba(99,102,241,.15)',colorText:'#818cf8',
    conducting:'Staff Selection Commission',
    posts:'Inspector (IT/CB/CE), Asst Section Officer, Auditor, UDC, DEO, etc.',
    vacancies:'~17,000',
    eligibility:'Graduate (21-32 yrs, varies by post)',
    mode:'CBT (Online)',
    language:'English & Hindi',
    status:'active',
    notification:'Sept 2024',
    applyLast:'Oct 2024',
    tier1:'Jan–March 2025',
    tier2:'June–July 2025',
    result:'Oct 2025',
    admitCardUrl:'https://ssc.nic.in/',
    syllabus:{
      'Tier I — General Intelligence':['Analogy','Series','Coding-Decoding','Directions','Blood Relations','Puzzles'],
      'Tier I — General Awareness':['History','Geography','Polity','Economics','Science','Current Affairs'],
      'Tier I — Quantitative Aptitude':['Number System','Ratio & Proportion','Percentage','Profit-Loss','Geometry','Trigonometry','DI'],
      'Tier I — English':['Reading Comprehension','Error Spotting','Fill in Blanks','One Word Sub','Cloze Test'],
      'Tier II — Mathematical Abilities':['Advanced Maths','Statistics (for JSO)'],
      'Tier II — English Language':['Grammar','Vocabulary','Comprehension'],
    },
    pattern:[
      {stage:'Tier I (Screening)',papers:'4 Sections x 25Q = 100Q',duration:'60 min',marks:'200'},
      {stage:'Tier II (Main)',papers:'Session I (3 hrs) + Session II (2.15 hrs)',duration:'5+ hrs',marks:'690'},
    ],
    cutoffs:[
      {year:'2023',general:'146 (T1)',obc:'138',sc:'130',st:'125',ews:'140'},
      {year:'2022',general:'144',obc:'136',sc:'129',st:'122',ews:'138'},
      {year:'2021',general:'142',obc:'134',sc:'127',st:'120',ews:'136'},
    ],
    materials:[
      {icon:'📖',title:'Kiran SSC CGL Guide',type:'Book','desc':'Complete guide'},
      {icon:'📋',title:'Previous Year Papers',type:'PDF','desc':'2010–2024'},
      {icon:'🎥',title:'SSC Adda YouTube',type:'Free','desc':'Video lectures'},
      {icon:'📘',title:'Rakesh Yadav Maths',type:'Book','desc':'Quantitative'},
    ],
  },
  {
    id:'rrb_ntpc',title:'RRB Non-Technical Popular Categories (NTPC)',
    short:'RRB NTPC',icon:'🚂',state:'Central',type:'central',
    category:['railway','central'],
    colorBg:'rgba(16,185,129,.15)',colorText:'#34d399',
    conducting:'Railway Recruitment Boards (21 RRBs)',
    posts:'Junior Clerk, Accounts Clerk, Junior Time Keeper, Commercial cum Ticket Clerk, Traffic Asst, Goods Guard, Sr Commercial cum Ticket Clerk, Sr Clerk cum Typist, JSA, Sr Time Keeper, Commercial Apprentice, Station Master',
    vacancies:'~11,558',
    eligibility:'10+2 to Graduation (18-33 yrs)',
    mode:'CBT (Online)',
    language:'15 languages',
    status:'active',
    notification:'Sept 2024',
    applyLast:'Oct 2024',
    cbt1:'Feb–April 2025',
    cbt2:'June 2025',
    skill:'July–Aug 2025',
    result:'Dec 2025',
    admitCardUrl:'https://indianrailways.gov.in/',
    syllabus:{
      'Mathematics':['Number System','Decimals','Fractions','LCM & HCF','Ratio & Proportion','Percentage','Mensuration','Time & Work','Time & Distance','SI & CI','Profit & Loss','Elementary Algebra','Geometry','Trigonometry'],
      'General Intelligence':['Analogies','Completion of Number/Alphabetic Series','Coding-Decoding','Directions','Data Sufficiency','Statement Conclusion','Venn Diagrams','Blood Relations'],
      'General Awareness':['Current Events (National & International)','Games & Sports','Art & Culture','Geography','Economics','Politics','Science'],
    },
    pattern:[
      {stage:'CBT Stage 1',papers:'Maths 30Q + GI&R 30Q + GA 40Q = 100Q',duration:'90 min',marks:'100'},
      {stage:'CBT Stage 2',papers:'Maths 35Q + GI&R 35Q + GA 50Q = 120Q',duration:'90 min',marks:'120'},
      {stage:'CBAT / Typing Skill Test',papers:'Aptitude for Station Master; Typing for Clerk posts',duration:'Varies',marks:'Qualifying'},
    ],
    cutoffs:[
      {year:'2019 Cycle',general:'70 (CBT1)',obc:'65',sc:'62',st:'58',ews:'68'},
      {year:'2016 Cycle',general:'75',obc:'70',sc:'67',st:'62',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'Arihant RRB NTPC Guide',type:'Book','desc':'Complete guide'},
      {icon:'📋',title:'RRB Previous Papers',type:'PDF','desc':'All years'},
      {icon:'🎥',title:'Exampur YouTube',type:'Free','desc':'Free classes'},
    ],
  },
  {
    id:'rrb_groupd',title:'RRB Group D (Level 1)',
    short:'RRB Group D',icon:'🚂',state:'Central',type:'central',
    category:['railway','central','group'],
    colorBg:'rgba(16,185,129,.15)',colorText:'#34d399',
    conducting:'Railway Recruitment Boards',
    posts:'Track Maintainer, Helper (Electrical/Mechanical/Signal & Telecom), Porter, Pointsman, Gateman',
    vacancies:'~32,000',
    eligibility:'10th Pass + ITI or Equivalent (18-33 yrs)',
    mode:'CBT + PET',
    language:'15 languages',
    status:'upcoming',
    notification:'Jan 2025',
    applyLast:'Feb 2025',
    exam:'May–June 2025',
    pet:'Aug 2025',
    result:'Nov 2025',
    syllabus:{
      'Mathematics':['Number System','BODMAS','Decimals & Fractions','LCM/HCF','Ratio','Percentage','Mensuration','Time/Work/Distance','SI/CI','Profit/Loss','Geometry','Trigonometry'],
      'General Intelligence & Reasoning':['Analogy','Coding-Decoding','Blood Relations','Series','Puzzles','Non-verbal'],
      'General Science':['Physics (10th level)','Chemistry (10th level)','Life Sciences (10th level)'],
      'General Awareness':['Current Affairs','Sports','Art & Culture','Geography','Polity','Economy'],
    },
    pattern:[
      {stage:'CBT (Online)',papers:'Maths 25Q + GI&R 30Q + GS 25Q + GA 20Q = 100Q',duration:'90 min',marks:'100'},
      {stage:'PET (Physical)',papers:'Male: 35kg carry 100m in 2min; 1000m in 4.15min; Female: 20kg in 2min; 1000m in 5.40min',duration:'As specified',marks:'Qualifying'},
      {stage:'Document Verification',papers:'Medical + Document Check',duration:'—',marks:'Qualifying'},
    ],
    cutoffs:[
      {year:'2022 Cycle',general:'58',obc:'54',sc:'50',st:'46',ews:'56'},
      {year:'2018 Cycle',general:'55',obc:'50',sc:'48',st:'44',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'RRB Group D Guide',type:'Book','desc':'Arihant / Kiran'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All CBT papers'},
    ],
  },
  {
    id:'ibps_po',title:'IBPS Probationary Officer (PO)',
    short:'IBPS PO',icon:'🏦',state:'Central',type:'central',
    category:['banking','central'],
    colorBg:'rgba(59,130,246,.15)',colorText:'#60a5fa',
    conducting:'Institute of Banking Personnel Selection',
    posts:'Probationary Officer / Management Trainee in 11 PSU Banks',
    vacancies:'~4,000',
    eligibility:'Any Graduate (20-30 yrs)',
    mode:'Online CBT + Interview',
    language:'English & Hindi',
    status:'upcoming',
    notification:'June 2025',
    applyLast:'July 2025',
    prelims:'Oct 2025',
    mains:'Nov 2025',
    interview:'Dec 2025–Jan 2026',
    syllabus:{
      'Prelims — English Language':['Reading Comprehension','Cloze Test','Parajumbles','Error Detection','Fill in Blanks'],
      'Prelims — Quantitative Aptitude':['Data Interpretation','Quadratic Equation','Number Series','Simplification','Miscellaneous Arithmetic'],
      'Prelims — Reasoning Ability':['Puzzles & Seating','Syllogism','Inequality','Coding-Decoding','Blood Relations','Input-Output','Direction Sense'],
      'Mains — Reasoning & Computer':['Advanced Reasoning','Computer Awareness','Machine Input'],
      'Mains — English Language':['RC','Grammar','Vocabulary','Essay Writing'],
      'Mains — Data Analysis':['DI (Tables/Charts/Graphs)','Caselet DI','Arithmetic'],
      'Mains — General/Economy/Banking Awareness':['Banking Awareness','Financial Awareness','Current Affairs'],
    },
    pattern:[
      {stage:'Prelims',papers:'English 30Q + Quant 35Q + Reasoning 35Q = 100Q',duration:'20+20+20=60 min',marks:'100'},
      {stage:'Mains',papers:'Reasoning+Computer 45Q + Eng 35Q + DI+Analysis 35Q + GA/Economy 40Q + Essay+Letter',duration:'4 hrs',marks:'200+25'},
      {stage:'Interview',papers:'Personal Interview',duration:'~15 min',marks:'100'},
    ],
    cutoffs:[
      {year:'2023',general:'52.50 (Prelims)',obc:'50.75',sc:'45.25',st:'41.00',ews:'51.00'},
      {year:'2022',general:'51.75',obc:'49.50',sc:'44.00',st:'40.25',ews:'50.25'},
    ],
    materials:[
      {icon:'📖',title:'Oliveboard IBPS PO',type:'App','desc':'Mock tests'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All IBPS papers'},
      {icon:'📘',title:'Arun Sharma Quant',type:'Book','desc':'Quantitative'},
      {icon:'📙',title:'Plinth to Paramount',type:'Book','desc':'English grammar'},
    ],
  },
  {
    id:'nda',title:'NDA & NA Examination',
    short:'NDA',icon:'⚔️',state:'Central',type:'central',
    category:['defence','central'],
    colorBg:'rgba(239,68,68,.15)',colorText:'#f87171',
    conducting:'Union Public Service Commission',
    posts:'Army, Navy & Air Force — Permanent Commission',
    vacancies:'~400 (NDA I) + 400 (NDA II)',
    eligibility:'12th Pass PCM for Navy/AF; Any stream for Army (16.5–19.5 yrs)',
    mode:'Offline (Written) + SSB',
    language:'English & Hindi',
    status:'active',
    notification:'Dec 2024 (NDA I) / May 2025 (NDA II)',
    applyLast:'Jan 2025 / June 2025',
    written:'April 2025 / Sept 2025',
    ssb:'June–Sept 2025',
    result:'Dec 2025',
    admitCardUrl:'https://upsc.gov.in/',
    syllabus:{
      'Mathematics (300M)':['Algebra','Matrices & Determinants','Trigonometry','Analytical Geometry 2D&3D','Differential Calculus','Integral Calculus','Vector Algebra','Statistics & Probability'],
      'GAT — English (200M)':['Grammar','Vocabulary','Comprehension','Composition'],
      'GAT — General Knowledge (400M)':['Physics','Chemistry','General Science','History','Freedom Movement','Geography','Current Events'],
    },
    pattern:[
      {stage:'Written — Mathematics',papers:'120 Questions',duration:'2.5 hrs',marks:'300'},
      {stage:'Written — GAT',papers:'150 Questions',duration:'2.5 hrs',marks:'600'},
      {stage:'SSB Interview',papers:'Psychological Tests + GTO + Interview + Conference',duration:'5 days',marks:'900'},
    ],
    cutoffs:[
      {year:'2023 NDA II',general:'(Written) 360 / (Final) 699',obc:'—',sc:'—',st:'—',ews:'—'},
      {year:'2022 NDA II',general:'355 / 695',obc:'—',sc:'—',st:'—',ews:'—'},
    ],
    materials:[
      {icon:'📖',title:'Pathfinder NDA/NA',type:'Book','desc':'Arihant'},
      {icon:'📋',title:'Previous 10 Years',type:'PDF','desc':'Solved papers'},
      {icon:'🎥',title:'Study IQ Defence',type:'YouTube','desc':'Free videos'},
    ],
  },

  // ─── ANDHRA PRADESH ───
  {
    id:'ap_group1',title:'APPSC Group I Services',
    short:'APPSC Group 1',icon:'🏛️',state:'Andhra Pradesh',type:'state',
    category:['state','group'],
    colorBg:'rgba(139,92,246,.15)',colorText:'#a78bfa',
    conducting:'Andhra Pradesh Public Service Commission',
    posts:'Deputy Collector, DSP, Commercial Tax Officer, Regional Transport Officer, DVO, AEE (Civil)',
    vacancies:'~120',
    eligibility:'Any Degree (21-42 yrs)',
    mode:'Offline (Written)',
    language:'Telugu & English',
    status:'upcoming',
    notification:'Feb 2025',
    applyLast:'March 2025',
    prelims:'June 2025',
    mains:'Oct 2025',
    interview:'Dec 2025',
    admitCardUrl:'https://psc.ap.gov.in/',
    syllabus:{
      'Paper I — History & Culture':['AP History','National Movement','Indian Culture','AP Festivals & Arts'],
      'Paper II — Geography & Environment':['AP Geography','Rivers','Forests','Environment & Ecology'],
      'Paper III — Indian Polity & Constitution':['Constitution','Governance','AP Reorganization Act','Panchayati Raj'],
      'Paper IV — Economy':['Indian Economy','AP Economy','Development Programmes','Budget & Fiscal Policy'],
      'Paper V — Science & Technology':['Physics / Chemistry / Bio basics','IT & Computers','Space Technology'],
      'Paper VI — Current Affairs':['State & National Events','Awards','Sports','New Appointments'],
    },
    pattern:[
      {stage:'Preliminary (Screening)',papers:'150Q MCQ — General Studies',duration:'150 min',marks:'150'},
      {stage:'Main Exam',papers:'6 GS Papers + 1 Optional Paper',duration:'3 hrs each',marks:'1800'},
      {stage:'Interview (Viva-Voce)',papers:'Personality Assessment',duration:'—',marks:'75'},
    ],
    cutoffs:[
      {year:'2022–23',general:'Prelims: 85 / Mains: 925',obc:'81 / 890',sc:'77 / 855',st:'73 / 835',ews:'83 / 910'},
      {year:'2020–21',general:'80 / 900',obc:'76 / 870',sc:'72 / 840',st:'68 / 820',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'AP History — Shivaji',type:'Book','desc':'Telugu medium'},
      {icon:'📋',title:'APPSC Previous Papers',type:'PDF','desc':'All years'},
      {icon:'🎥',title:'APPSC Adda YouTube',type:'Free','desc':'Free classes'},
    ],
  },
  {
    id:'ap_group2',title:'APPSC Group II Services',
    short:'APPSC Group 2',icon:'🏛️',state:'Andhra Pradesh',type:'state',
    category:['state','group'],
    colorBg:'rgba(139,92,246,.15)',colorText:'#a78bfa',
    conducting:'Andhra Pradesh Public Service Commission',
    posts:'Mandal Parishad Development Officer, Extension Officer, Executive Officer Grade-I, etc.',
    vacancies:'~442',
    eligibility:'Any Degree (18-42 yrs)',
    mode:'Offline (Written)',
    language:'Telugu & English',
    status:'upcoming',
    notification:'March 2025',
    applyLast:'April 2025',
    prelims:'July 2025',
    mains:'Oct 2025',
    result:'Jan 2026',
    syllabus:{
      'Paper I — General Studies':['Indian History','Geography','Polity','Economy','Science & Technology','Current Affairs'],
      'Paper II — Social & Cultural History':['AP History','Culture','Literature','Movements'],
      'Paper III — Planning & Economy':['Indian Economy','AP Economy','Development','Planning'],
      'Paper IV — Science & Technology':['Physics','Chemistry','Biology','IT','Space'],
    },
    pattern:[
      {stage:'Preliminary (Screening)',papers:'150Q MCQ — General Studies',duration:'150 min',marks:'150'},
      {stage:'Main Exam',papers:'4 Papers — General Studies',duration:'3 hrs each',marks:'1500'},
    ],
    cutoffs:[
      {year:'2023',general:'Prelims: 90',obc:'85',sc:'80',st:'75',ews:'88'},
      {year:'2022',general:'88',obc:'83',sc:'78',st:'73',ews:'86'},
    ],
    materials:[
      {icon:'📖',title:'APPSC Group 2 Guide',type:'Book','desc':'Vijetha / Telugu Academy'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },
  {
    id:'ap_group4',title:'APPSC Group IV Services',
    short:'APPSC Group 4',icon:'🏛️',state:'Andhra Pradesh',type:'state',
    category:['state','group'],
    colorBg:'rgba(139,92,246,.15)',colorText:'#a78bfa',
    conducting:'Andhra Pradesh Public Service Commission',
    posts:'Junior Assistant, Junior Accountant, Typist, Stenographer',
    vacancies:'~670',
    eligibility:'Intermediate (18-42 yrs)',
    mode:'Offline (Written)',
    language:'Telugu & English',
    status:'upcoming',
    notification:'April 2025',
    applyLast:'May 2025',
    exam:'Aug 2025',
    result:'Nov 2025',
    syllabus:{
      'General Studies':['Indian History','Geography','Polity','Economy','Science','Current Affairs'],
      'Secretarial Abilities':['Mental Ability','Logical Reasoning','Comprehension','Re-arrangement of Sentences'],
      'General Mathematics':['Arithmetic','Algebra','Geometry','Statistics'],
      'English':['Grammar','Vocabulary','Comprehension'],
    },
    pattern:[
      {stage:'Written Exam',papers:'General Studies 50Q + Secretarial 40Q + Maths 30Q + English 30Q = 150Q',duration:'150 min',marks:'150'},
    ],
    cutoffs:[
      {year:'2023',general:'85',obc:'80',sc:'75',st:'70',ews:'83'},
      {year:'2022',general:'82',obc:'77',sc:'72',st:'67',ews:'80'},
    ],
    materials:[
      {icon:'📖',title:'APPSC Group 4 Guide',type:'Book','desc':'Vijetha'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── TELANGANA ───
  {
    id:'ts_group1',title:'TSPSC Group I Services',
    short:'TSPSC Group 1',icon:'🏛️',state:'Telangana',type:'state',
    category:['state','group'],
    colorBg:'rgba(34,197,94,.15)',colorText:'#22c55e',
    conducting:'Telangana State Public Service Commission',
    posts:'Deputy Collector, DSP, Commercial Tax Officer, Regional Transport Officer',
    vacancies:'~503',
    eligibility:'Any Degree (21-43 yrs)',
    mode:'Offline (Written)',
    language:'Telugu & English',
    status:'upcoming',
    notification:'Feb 2025',
    applyLast:'March 2025',
    prelims:'June 2025',
    mains:'Sept 2025',
    interview:'Dec 2025',
    syllabus:{
      'Paper I — General Studies':['Indian History','Geography','Polity','Economy','Science & Technology','Current Affairs'],
      'Paper II — History & Culture':['Telangana History','Culture','Literature','Movements'],
      'Paper III — Indian Polity':['Constitution','Governance','Public Administration'],
      'Paper IV — Economy':['Indian Economy','Telangana Economy','Development'],
      'Paper V — Science & Technology':['Physics','Chemistry','Biology','IT'],
      'Paper VI — Telangana Movement':['Telangana Statehood','Movements','Integration'],
    },
    pattern:[
      {stage:'Preliminary (Screening)',papers:'150Q MCQ — General Studies',duration:'150 min',marks:'150'},
      {stage:'Main Exam',papers:'6 Papers — General Studies',duration:'3 hrs each',marks:'1800'},
      {stage:'Interview (Viva-Voce)',papers:'Personality Assessment',duration:'—',marks:'75'},
    ],
    cutoffs:[
      {year:'2022–23',general:'Prelims: 88 / Mains: 950',obc:'83 / 920',sc:'78 / 890',st:'73 / 860',ews:'86 / 930'},
      {year:'2020–21',general:'85 / 920',obc:'80 / 890',sc:'75 / 860',st:'70 / 830',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'TSPSC Group 1 Guide',type:'Book','desc':'Vijetha / Telugu Academy'},
      {icon:'📋',title:'TSPSC Previous Papers',type:'PDF','desc':'All years'},
      {icon:'🎥',title:'TSPSC Adda YouTube',type:'Free','desc':'Free classes'},
    ],
  },
  {
    id:'ts_group2',title:'TSPSC Group II Services',
    short:'TSPSC Group 2',icon:'🏛️',state:'Telangana',type:'state',
    category:['state','group'],
    colorBg:'rgba(34,197,94,.15)',colorText:'#22c55e',
    conducting:'Telangana State Public Service Commission',
    posts:'Mandal Revenue Officer, Extension Officer, Executive Officer Grade-I',
    vacancies:'~444',
    eligibility:'Any Degree (18-44 yrs)',
    mode:'Offline (Written)',
    language:'Telugu & English',
    status:'upcoming',
    notification:'March 2025',
    applyLast:'April 2025',
    prelims:'July 2025',
    mains:'Oct 2025',
    result:'Jan 2026',
    syllabus:{
      'Paper I — General Studies':['Indian History','Geography','Polity','Economy','Science & Technology','Current Affairs'],
      'Paper II — History & Culture':['Telangana History','Culture','Literature','Movements'],
      'Paper III — Indian Polity':['Constitution','Governance','Public Administration'],
      'Paper IV — Economy':['Indian Economy','Telangana Economy','Development'],
      'Paper V — Science & Technology':['Physics','Chemistry','Biology','IT'],
    },
    pattern:[
      {stage:'Preliminary (Screening)',papers:'150Q MCQ — General Studies',duration:'150 min',marks:'150'},
      {stage:'Main Exam',papers:'5 Papers — General Studies',duration:'3 hrs each',marks:'1500'},
    ],
    cutoffs:[
      {year:'2023',general:'Prelims: 92',obc:'87',sc:'82',st:'77',ews:'90'},
      {year:'2022',general:'89',obc:'84',sc:'79',st:'74',ews:'87'},
    ],
    materials:[
      {icon:'📖',title:'TSPSC Group 2 Guide',type:'Book','desc':'Vijetha'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── UTTAR PRADESH ───
  {
    id:'up_police_si',title:'UP Police Sub-Inspector (SI)',
    short:'UP Police SI',icon:'👮',state:'Uttar Pradesh',type:'state',
    category:['police','state'],
    colorBg:'rgba(239,68,68,.15)',colorText:'#f87171',
    conducting:'Uttar Pradesh Police Recruitment and Promotion Board (UPPRPB)',
    posts:'Sub-Inspector (Civil Police / Platoon Commander / Fire Brigade)',
    vacancies:'~9,192',
    eligibility:'Graduate (21-28 yrs)',
    mode:'Online CBT + PST + PET',
    language:'Hindi & English',
    status:'upcoming',
    notification:'Feb 2025',
    applyLast:'March 2025',
    prelims:'June 2025',
    mains:'Aug 2025',
    pst:'Oct 2025',
    pet:'Nov 2025',
    syllabus:{
      'General Hindi':['Grammar','Vocabulary','Comprehension','Synonyms/Antonyms'],
      'Law & Constitution':['Indian Penal Code','Criminal Procedure Code','Indian Evidence Act','Constitution'],
      'General Knowledge':['History','Geography','Polity','Economy','Science','Current Affairs'],
      'Numerical & Mental Ability':['Arithmetic','Reasoning','Mental Ability','Data Interpretation'],
      'Mental Aptitude':['Intelligence','Reasoning','Comprehension','Problem Solving'],
    },
    pattern:[
      {stage:'Preliminary Exam',papers:'General Studies 160Q + General Hindi 40Q = 200Q',duration:'170 min',marks:'400'},
      {stage:'Main Exam',papers:'General Studies 100Q + General Hindi 100Q = 200Q',duration:'180 min',marks:'400'},
      {stage:'PST (Physical Standard Test)',papers:'Height, Chest, Weight as per category',duration:'—',marks:'Qualifying'},
      {stage:'PET (Physical Efficiency Test)',papers:'Running, Long Jump, High Jump',duration:'As specified',marks:'Qualifying'},
    ],
    cutoffs:[
      {year:'2022',general:'Prelims: 380 / Mains: 360',obc:'375 / 355',sc:'365 / 345',st:'360 / 340',ews:'378 / 358'},
      {year:'2021',general:'385 / 365',obc:'380 / 360',sc:'370 / 350',st:'365 / 345',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'UP Police SI Guide',type:'Book','desc':'Arihant / Lucent'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
      {icon:'🎥',title:'UP Police Adda YouTube',type:'Free','desc':'Free classes'},
    ],
  },
  {
    id:'up_police_constable',title:'UP Police Constable',
    short:'UP Constable',icon:'👮',state:'Uttar Pradesh',type:'state',
    category:['police','state','group'],
    colorBg:'rgba(239,68,68,.15)',colorText:'#f87171',
    conducting:'Uttar Pradesh Police Recruitment and Promotion Board (UPPRPB)',
    posts:'Constable (Civil Police / PAC / Fire Brigade)',
    vacancies:'~60,000',
    eligibility:'10+2 (18-25 yrs)',
    mode:'Online CBT + PST + PET',
    language:'Hindi & English',
    status:'upcoming',
    notification:'March 2025',
    applyLast:'April 2025',
    prelims:'July 2025',
    mains:'Sept 2025',
    pst:'Nov 2025',
    pet:'Dec 2025',
    syllabus:{
      'General Knowledge':['History','Geography','Polity','Economy','Science','Current Affairs'],
      'General Hindi':['Grammar','Vocabulary','Comprehension','Synonyms/Antonyms'],
      'Numerical & Mental Ability':['Arithmetic','Reasoning','Mental Ability','Data Interpretation'],
      'Mental Aptitude':['Intelligence','Reasoning','Comprehension','Problem Solving'],
    },
    pattern:[
      {stage:'Preliminary Exam',papers:'General Studies 150Q + General Hindi 50Q = 200Q',duration:'120 min',marks:'300'},
      {stage:'Main Exam',papers:'General Studies 150Q + General Hindi 50Q = 200Q',duration:'120 min',marks:'300'},
      {stage:'PST (Physical Standard Test)',papers:'Height, Chest, Weight as per category',duration:'—',marks:'Qualifying'},
      {stage:'PET (Physical Efficiency Test)',papers:'Running, Long Jump, High Jump',duration:'As specified',marks:'Qualifying'},
    ],
    cutoffs:[
      {year:'2023',general:'Prelims: 245 / Mains: 240',obc:'240 / 235',sc:'230 / 225',st:'225 / 220',ews:'243 / 238'},
      {year:'2022',general:'250 / 245',obc:'245 / 240',sc:'235 / 230',st:'230 / 225',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'UP Constable Guide',type:'Book','desc':'Arihant'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── MAHARASHTRA ───
  {
    id:'mh_mpsc_sti',title:'MPSC State Tax Inspector (STI)',
    short:'MPSC STI',icon:'🏛️',state:'Maharashtra',type:'state',
    category:['state','revenue'],
    colorBg:'rgba(168,85,247,.15)',colorText:'#a855f7',
    conducting:'Maharashtra Public Service Commission',
    posts:'State Tax Inspector',
    vacancies:'~200',
    eligibility:'Any Graduate (19-38 yrs)',
    mode:'Offline (Written)',
    language:'Marathi & English',
    status:'upcoming',
    notification:'Jan 2025',
    applyLast:'Feb 2025',
    prelims:'May 2025',
    mains:'Aug 2025',
    interview:'Nov 2025',
    syllabus:{
      'Paper I — Marathi':['Grammar','Vocabulary','Comprehension','Translation'],
      'Paper I — English':['Grammar','Vocabulary','Comprehension','Translation'],
      'Paper I — General Studies':['History','Geography','Polity','Economy','Science','Current Affairs'],
      'Paper II — Commerce':['Accounting','Auditing','Business Law','Taxation'],
      'Paper II — General Studies':['Indian Polity','Economy','Science & Technology'],
    },
    pattern:[
      {stage:'Preliminary (Screening)',papers:'150Q MCQ — General Studies',duration:'120 min',marks:'150'},
      {stage:'Main Exam',papers:'Paper I (GS + Languages) + Paper II (Commerce + GS)',duration:'2 hrs each',marks:'400'},
      {stage:'Interview (Viva-Voce)',papers:'Personality Assessment',duration:'—',marks:'50'},
    ],
    cutoffs:[
      {year:'2023',general:'Prelims: 85 / Mains: 320',obc:'80 / 300',sc:'75 / 280',st:'70 / 260',ews:'83 / 315'},
      {year:'2022',general:'82 / 310',obc:'77 / 290',sc:'72 / 270',st:'67 / 250',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'MPSC STI Guide',type:'Book','desc':'Unique Publications'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── RAJASTHAN ───
  {
    id:'rj_police_constable',title:'Rajasthan Police Constable',
    short:'Rajasthan Constable',icon:'👮',state:'Rajasthan',type:'state',
    category:['police','state','group'],
    colorBg:'rgba(251,146,60,.15)',colorText:'#fb923c',
    conducting:'Rajasthan Police',
    posts:'Constable (General Duty)',
    vacancies:'~15,000',
    eligibility:'10th Pass (18-25 yrs)',
    mode:'Online CBT + PST + PET',
    language:'Hindi & English',
    status:'upcoming',
    notification:'Feb 2025',
    applyLast:'March 2025',
    exam:'June 2025',
    pst:'Aug 2025',
    pet:'Sept 2025',
    syllabus:{
      'General Knowledge':['History','Geography','Polity','Economy','Science','Current Affairs'],
      'General Science':['Physics','Chemistry','Biology','Computer Science'],
      'Mathematics':['Arithmetic','Algebra','Geometry','Statistics'],
      'General Reasoning':['Logical Reasoning','Mental Ability','Data Interpretation'],
      'Agriculture':['Basic Agriculture','Horticulture','Animal Husbandry'],
      'Animal Husbandry':['Livestock','Poultry','Dairy Farming'],
    },
    pattern:[
      {stage:'Written Exam',papers:'GS 80Q + Science 60Q + Maths 45Q + Reasoning 45Q + Agri/AH 20Q = 250Q',duration:'90 min',marks:'80'},
      {stage:'PST (Physical Standard Test)',papers:'Height, Chest, Weight as per category',duration:'—',marks:'Qualifying'},
      {stage:'PET (Physical Efficiency Test)',papers:'Running, Long Jump, High Jump',duration:'As specified',marks:'Qualifying'},
    ],
    cutoffs:[
      {year:'2023',general:'55',obc:'50',sc:'45',st:'40',ews:'53'},
      {year:'2022',general:'58',obc:'53',sc:'48',st:'43',ews:'56'},
    ],
    materials:[
      {icon:'📖',title:'Rajasthan Constable Guide',type:'Book','desc':'RBD Publications'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── TAMIL NADU ───
  {
    id:'tn_trb_pg',title:'TN TRB Post Graduate Assistant (PG Asst)',
    short:'TN TRB PG Asst',icon:'📚',state:'Tamil Nadu',type:'state',
    category:['teacher','state'],
    colorBg:'rgba(34,197,94,.15)',colorText:'#22c55e',
    conducting:'Tamil Nadu Teachers Recruitment Board',
    posts:'Post Graduate Assistant in Government Schools',
    vacancies:'~2,500',
    eligibility:'PG Degree in relevant subject + B.Ed (21-50 yrs)',
    mode:'Online CBT',
    language:'Tamil & English',
    status:'upcoming',
    notification:'March 2025',
    applyLast:'April 2025',
    exam:'July 2025',
    result:'Oct 2025',
    syllabus:{
      'Tamil Language':['Grammar','Literature','Composition','Translation'],
      'English Language':['Grammar','Literature','Composition','Translation'],
      'Mathematics':['Algebra','Calculus','Geometry','Statistics'],
      'Physics':['Mechanics','Electricity','Magnetism','Optics'],
      'Chemistry':['Organic','Inorganic','Physical Chemistry'],
      'Botany':['Plant Physiology','Genetics','Ecology'],
      'Zoology':['Animal Physiology','Genetics','Ecology'],
      'History':['Ancient','Medieval','Modern India','World History'],
      'Geography':['Physical','Human','Economic Geography'],
      'Political Science':['Political Theory','Indian Government','International Relations'],
      'Economics':['Micro/Macro Economics','Indian Economy','Public Finance'],
      'Commerce':['Accountancy','Business Studies','Management'],
      'Computer Science':['Programming','Data Structures','Databases'],
    },
    pattern:[
      {stage:'Written Exam',papers:'Main Subject 110Q + General Knowledge 30Q = 140Q',duration:'180 min',marks:'140'},
    ],
    cutoffs:[
      {year:'2023',general:'90',obc:'85',sc:'80',st:'75',ews:'88'},
      {year:'2022',general:'88',obc:'83',sc:'78',st:'73',ews:'86'},
    ],
    materials:[
      {icon:'📖',title:'TN TRB PG Asst Guide',type:'Book','desc':'Sakthi Publications'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── KARNATAKA ───
  {
    id:'ka_kpsc_gae',title:'KPSC Group A & Group B Exams',
    short:'KPSC GAE',icon:'🏛️',state:'Karnataka',type:'state',
    category:['state','group'],
    colorBg:'rgba(59,130,246,.15)',colorText:'#60a5fa',
    conducting:'Karnataka Public Service Commission',
    posts:'Deputy Superintendent of Police, Commercial Tax Officer, Assistant Commissioner, etc.',
    vacancies:'~300',
    eligibility:'Any Graduate (21-35 yrs)',
    mode:'Offline (Written)',
    language:'Kannada & English',
    status:'upcoming',
    notification:'Feb 2025',
    applyLast:'March 2025',
    prelims:'June 2025',
    mains:'Sept 2025',
    interview:'Dec 2025',
    syllabus:{
      'General Studies':['Indian History','Geography','Polity','Economy','Science','Current Affairs'],
      'General Studies (CSAT)':['Comprehension','Reasoning','Data Interpretation','Basic Numeracy'],
      'Odia Language':['Grammar','Literature','Composition','Translation'],
      'English Language':['Grammar','Literature','Composition','Translation'],
      'Essay':['Current Topics','Social Issues','Development'],
      'Optional Subject':['Selected by candidate from 22 options'],
    },
    pattern:[
      {stage:'Preliminary (Screening)',papers:'150Q MCQ — General Studies',duration:'120 min',marks:'150'},
      {stage:'Main Exam',papers:'GS I + GS II + Odia + English + Essay + Optional I + Optional II',duration:'3 hrs each',marks:'1400'},
      {stage:'Interview (Viva-Voce)',papers:'Personality Assessment',duration:'—',marks:'150'},
    ],
    cutoffs:[
      {year:'2023',general:'Prelims: 92 / Mains: 1050',obc:'87 / 1000',sc:'82 / 950',st:'77 / 900',ews:'90 / 1025'},
      {year:'2022',general:'89 / 1020',obc:'84 / 970',sc:'79 / 920',st:'74 / 870',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'KPSC GAE Guide',type:'Book','desc':'Ramesh Publications'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── KERALA ───
  {
    id:'kl_psc_ldc',title:'Kerala PSC Lower Division Clerk (LDC)',
    short:'Kerala PSC LDC',icon:'🏛️',state:'Kerala',type:'state',
    category:['state','group'],
    colorBg:'rgba(16,185,129,.15)',colorText:'#34d399',
    conducting:'Kerala Public Service Commission',
    posts:'Lower Division Clerk in various departments',
    vacancies:'~1,000',
    eligibility:'Plus Two (18-36 yrs)',
    mode:'Online CBT',
    language:'Malayalam & English',
    status:'upcoming',
    notification:'March 2025',
    applyLast:'April 2025',
    exam:'July 2025',
    result:'Oct 2025',
    syllabus:{
      'General Knowledge':['History','Geography','Polity','Economy','Science','Current Affairs'],
      'General English':['Grammar','Vocabulary','Comprehension','Synonyms/Antonyms'],
      'Simple Arithmetic':['Numbers','Fractions','Percentages','Ratios'],
      'Mental Ability':['Reasoning','Problem Solving','Data Interpretation'],
    },
    pattern:[
      {stage:'Written Exam',papers:'GK 50Q + English 40Q + Arithmetic 30Q + Mental Ability 30Q = 150Q',duration:'75 min',marks:'150'},
    ],
    cutoffs:[
      {year:'2023',general:'85',obc:'80',sc:'75',st:'70',ews:'83'},
      {year:'2022',general:'82',obc:'77',sc:'72',st:'67',ews:'80'},
    ],
    materials:[
      {icon:'📖',title:'Kerala PSC LDC Guide',type:'Book','desc':'PSC Publications'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── WEST BENGAL ───
  {
    id:'wb_police_si',title:'West Bengal Police Sub-Inspector (SI)',
    short:'WB Police SI',icon:'👮',state:'West Bengal',type:'state',
    category:['police','state'],
    colorBg:'rgba(239,68,68,.15)',colorText:'#f87171',
    conducting:'West Bengal Police Recruitment Board',
    posts:'Sub-Inspector (UB / Lady Sub-Inspector)',
    vacancies:'~1,000',
    eligibility:'Any Graduate (20-32 yrs)',
    mode:'Online CBT + PST + PET',
    language:'Bengali & English',
    status:'upcoming',
    notification:'Feb 2025',
    applyLast:'March 2025',
    prelims:'June 2025',
    mains:'Aug 2025',
    pst:'Oct 2025',
    pet:'Nov 2025',
    syllabus:{
      'General Studies':['History','Geography','Polity','Economy','Science','Current Affairs'],
      'Logical & Analytical Reasoning':['Reasoning','Mental Ability','Data Interpretation'],
      'Arithmetic':['Numbers','Fractions','Percentages','Ratios','Profit-Loss'],
      'English':['Grammar','Vocabulary','Comprehension','Synonyms/Antonyms'],
      'Bengali':['Grammar','Literature','Composition','Translation'],
    },
    pattern:[
      {stage:'Preliminary Exam',papers:'General Studies 50Q + Logical Reasoning 25Q + Arithmetic 25Q = 100Q',duration:'90 min',marks:'200'},
      {stage:'Main Exam',papers:'General Studies 25Q + Logical Reasoning 20Q + Arithmetic 20Q + English 15Q + Bengali 15Q = 95Q',duration:'90 min',marks:'190'},
      {stage:'PST (Physical Standard Test)',papers:'Height, Chest, Weight as per category',duration:'—',marks:'Qualifying'},
      {stage:'PET (Physical Efficiency Test)',papers:'Running, Long Jump, High Jump',duration:'As specified',marks:'Qualifying'},
    ],
    cutoffs:[
      {year:'2023',general:'Prelims: 160 / Mains: 140',obc:'155 / 135',sc:'150 / 130',st:'145 / 125',ews:'158 / 138'},
      {year:'2022',general:'165 / 145',obc:'160 / 140',sc:'155 / 135',st:'150 / 130',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'WB Police SI Guide',type:'Book','desc':'WB Publications'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── GUJARAT ───
  {
    id:'gj_gpsc_class3',title:'GPSC Class III Posts',
    short:'GPSC Class 3',icon:'🏛️',state:'Gujarat',type:'state',
    category:['state','group'],
    colorBg:'rgba(168,85,247,.15)',colorText:'#a855f7',
    conducting:'Gujarat Public Service Commission',
    posts:'Junior Clerk, Senior Clerk, Assistant, etc.',
    vacancies:'~2,000',
    eligibility:'Any Graduate (21-35 yrs)',
    mode:'Online CBT',
    language:'Gujarati & English',
    status:'upcoming',
    notification:'March 2025',
    applyLast:'April 2025',
    exam:'July 2025',
    result:'Oct 2025',
    syllabus:{
      'General Studies':['History','Geography','Polity','Economy','Science','Current Affairs'],
      'Gujarati Language':['Grammar','Literature','Composition','Translation'],
      'English Language':['Grammar','Literature','Composition','Translation'],
      'Quantitative Aptitude':['Arithmetic','Algebra','Geometry','Statistics'],
      'Reasoning':['Logical Reasoning','Mental Ability','Data Interpretation'],
    },
    pattern:[
      {stage:'Written Exam',papers:'GS 50Q + Gujarati 30Q + English 20Q + Quant 30Q + Reasoning 30Q = 160Q',duration:'120 min',marks:'160'},
    ],
    cutoffs:[
      {year:'2023',general:'95',obc:'90',sc:'85',st:'80',ews:'93'},
      {year:'2022',general:'92',obc:'87',sc:'82',st:'77',ews:'90'},
    ],
    materials:[
      {icon:'📖',title:'GPSC Class 3 Guide',type:'Book','desc':'Pinnacle Publications'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── PUNJAB ───
  {
    id:'pb_police_constable',title:'Punjab Police Constable',
    short:'Punjab Constable',icon:'👮',state:'Punjab',type:'state',
    category:['police','state','group'],
    colorBg:'rgba(239,68,68,.15)',colorText:'#f87171',
    conducting:'Punjab Staff Selection Commission (HSSC)',
    posts:'Constable (General Duty)',
    vacancies:'~2,000',
    eligibility:'10+2 (18-28 yrs)',
    mode:'Online CBT + PST + PET',
    language:'Punjabi & English',
    status:'upcoming',
    notification:'Feb 2025',
    applyLast:'March 2025',
    exam:'June 2025',
    pst:'Aug 2025',
    pet:'Sept 2025',
    syllabus:{
      'General Knowledge':['History','Geography','Polity','Economy','Science','Current Affairs'],
      'Punjabi Language':['Grammar','Vocabulary','Comprehension','Synonyms/Antonyms'],
      'English Language':['Grammar','Vocabulary','Comprehension','Synonyms/Antonyms'],
      'Quantitative Aptitude':['Arithmetic','Algebra','Geometry','Statistics'],
      'Reasoning':['Logical Reasoning','Mental Ability','Data Interpretation'],
    },
    pattern:[
      {stage:'Written Exam',papers:'GK 40Q + Punjabi 20Q + English 20Q + Quant 30Q + Reasoning 30Q = 140Q',duration:'120 min',marks:'140'},
      {stage:'PST (Physical Standard Test)',papers:'Height, Chest, Weight as per category',duration:'—',marks:'Qualifying'},
      {stage:'PET (Physical Efficiency Test)',papers:'Running, Long Jump, High Jump',duration:'As specified',marks:'Qualifying'},
    ],
    cutoffs:[
      {year:'2023',general:'85',obc:'80',sc:'75',st:'70',ews:'83'},
      {year:'2022',general:'82',obc:'77',sc:'72',st:'67',ews:'80'},
    ],
    materials:[
      {icon:'📖',title:'Punjab Constable Guide',type:'Book','desc':'Punjab Publications'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── JHARKHAND ───
  {
    id:'jh_jssc_pgt',title:'JSSC Post Graduate Trained Teacher (PGT)',
    short:'JSSC PGT',icon:'📚',state:'Jharkhand',type:'state',
    category:['teacher','state'],
    colorBg:'rgba(34,197,94,.15)',colorText:'#22c55e',
    conducting:'Jharkhand Staff Selection Commission',
    posts:'Post Graduate Teacher in Government Schools',
    vacancies:'~1,500',
    eligibility:'PG Degree in relevant subject + B.Ed (21-40 yrs)',
    mode:'Online CBT',
    language:'Hindi & English',
    status:'upcoming',
    notification:'March 2025',
    applyLast:'April 2025',
    exam:'July 2025',
    result:'Oct 2025',
    syllabus:{
      'General Knowledge':['History','Geography','Polity','Economy','Science','Current Affairs'],
      'Hindi Language':['Grammar','Literature','Composition','Translation'],
      'English Language':['Grammar','Literature','Composition','Translation'],
      'Concerned Subject':['Subject-specific topics as per post'],
      'Teaching Aptitude':['Teaching Methods','Child Development','Educational Psychology'],
    },
    pattern:[
      {stage:'Written Exam',papers:'GK 40Q + Hindi 20Q + English 20Q + Subject 80Q + Teaching 20Q = 180Q',duration:'180 min',marks:'180'},
    ],
    cutoffs:[
      {year:'2023',general:'110',obc:'105',sc:'100',st:'95',ews:'108'},
      {year:'2022',general:'115',obc:'110',sc:'105',st:'100',ews:'113'},
    ],
    materials:[
      {icon:'📖',title:'JSSC PGT Guide',type:'Book','desc':'Jharkhand Publications'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── MADHYA PRADESH ───
  {
    id:'mp_police_si',title:'MP Police Sub-Inspector (SI)',
    short:'MP Police SI',icon:'👮',state:'Madhya Pradesh',type:'state',
    category:['police','state'],
    colorBg:'rgba(239,68,68,.15)',colorText:'#f87171',
    conducting:'Madhya Pradesh Professional Examination Board (MPPEB)',
    posts:'Sub-Inspector (GD)',
    vacancies:'~2,000',
    eligibility:'Any Graduate (18-33 yrs)',
    mode:'Online CBT + PST + PET',
    language:'Hindi & English',
    status:'upcoming',
    notification:'Feb 2025',
    applyLast:'March 2025',
    prelims:'June 2025',
    mains:'Aug 2025',
    pst:'Oct 2025',
    pet:'Nov 2025',
    syllabus:{
      'General Knowledge':['History','Geography','Polity','Economy','Science','Current Affairs'],
      'Reasoning & Mental Ability':['Logical Reasoning','Mental Ability','Data Interpretation'],
      'Mathematics':['Arithmetic','Algebra','Geometry','Statistics'],
      'English':['Grammar','Vocabulary','Comprehension','Synonyms/Antonyms'],
      'Hindi':['Grammar','Literature','Composition','Translation'],
    },
    pattern:[
      {stage:'Preliminary Exam',papers:'GK 40Q + Reasoning 30Q + Maths 30Q = 100Q',duration:'120 min',marks:'100'},
      {stage:'Main Exam',papers:'GK 50Q + Reasoning 30Q + Maths 20Q + English 20Q + Hindi 20Q = 140Q',duration:'180 min',marks:'140'},
      {stage:'PST (Physical Standard Test)',papers:'Height, Chest, Weight as per category',duration:'—',marks:'Qualifying'},
      {stage:'PET (Physical Efficiency Test)',papers:'Running, Long Jump, High Jump',duration:'As specified',marks:'Qualifying'},
    ],
    cutoffs:[
      {year:'2023',general:'Prelims: 65 / Mains: 95',obc:'60 / 90',sc:'55 / 85',st:'50 / 80',ews:'63 / 93'},
      {year:'2022',general:'68 / 98',obc:'63 / 93',sc:'58 / 88',st:'53 / 83',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'MP Police SI Guide',type:'Book','desc':'Arihant'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── BIHAR ───
  {
    id:'br_bpsc_68',title:'BPSC 68th Combined Competitive Exam',
    short:'BPSC 68th',icon:'🏛️',state:'Bihar',type:'state',
    category:['state','group'],
    colorBg:'rgba(168,85,247,.15)',colorText:'#a855f7',
    conducting:'Bihar Public Service Commission',
    posts:'Deputy Collector, DSP, District Commandant, etc.',
    vacancies:'~200',
    eligibility:'Any Graduate (20-37 yrs)',
    mode:'Offline (Written)',
    language:'Hindi & English',
    status:'upcoming',
    notification:'Feb 2025',
    applyLast:'March 2025',
    prelims:'June 2025',
    mains:'Sept 2025',
    interview:'Dec 2025',
    syllabus:{
      'General Studies':['Indian History','Geography','Polity','Economy','Science','Current Affairs'],
      'General Hindi':['Grammar','Literature','Composition','Translation'],
      'Essay':['Current Topics','Social Issues','Development'],
      'Optional Subject':['Selected by candidate from 34 options'],
    },
    pattern:[
      {stage:'Preliminary (Screening)',papers:'150Q MCQ — General Studies',duration:'120 min',marks:'150'},
      {stage:'Main Exam',papers:'GS Paper I + GS Paper II + Essay + Optional I + Optional II',duration:'3 hrs each',marks:'1200'},
      {stage:'Interview (Viva-Voce)',papers:'Personality Assessment',duration:'—',marks:'120'},
    ],
    cutoffs:[
      {year:'2023',general:'Prelims: 108 / Mains: 480',obc:'103 / 460',sc:'98 / 440',st:'93 / 420',ews:'106 / 475'},
      {year:'2022',general:'105 / 470',obc:'100 / 450',sc:'95 / 430',st:'90 / 410',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'BPSC Guide',type:'Book','desc':'Unique Publications'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── ODISHA ───
  {
    id:'or_opsc_ocs',title:'OPSC Odisha Civil Services (OCS)',
    short:'OPSC OCS',icon:'🏛️',state:'Odisha',type:'state',
    category:['state','group'],
    colorBg:'rgba(59,130,246,.15)',colorText:'#60a5fa',
    conducting:'Odisha Public Service Commission',
    posts:'Deputy Collector, DSP, Assistant Commissioner, etc.',
    vacancies:'~150',
    eligibility:'Any Graduate (21-32 yrs)',
    mode:'Offline (Written)',
    language:'Odia & English',
    status:'upcoming',
    notification:'Feb 2025',
    applyLast:'March 2025',
    prelims:'June 2025',
    mains:'Sept 2025',
    interview:'Dec 2025',
    syllabus:{
      'General Studies':['Indian History','Geography','Polity','Economy','Science','Current Affairs'],
      'General Studies (CSAT)':['Comprehension','Reasoning','Data Interpretation','Basic Numeracy'],
      'Odia Language':['Grammar','Literature','Composition','Translation'],
      'English Language':['Grammar','Literature','Composition','Translation'],
      'Essay':['Current Topics','Social Issues','Development'],
      'Optional Subject':['Selected by candidate from 22 options'],
    },
    pattern:[
      {stage:'Preliminary (Screening)',papers:'150Q MCQ — General Studies',duration:'120 min',marks:'150'},
      {stage:'Main Exam',papers:'GS I + GS II + Odia + English + Essay + Optional I + Optional II',duration:'3 hrs each',marks:'1400'},
      {stage:'Interview (Viva-Voce)',papers:'Personality Assessment',duration:'—',marks:'150'},
    ],
    cutoffs:[
      {year:'2023',general:'Prelims: 90 / Mains: 650',obc:'85 / 625',sc:'80 / 600',st:'75 / 575',ews:'88 / 640'},
      {year:'2022',general:'87 / 630',obc:'82 / 605',sc:'77 / 580',st:'72 / 555',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'OPSC OCS Guide',type:'Book','desc':'Odisha Publications'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── ASSAM ───
  {
    id:'as_police_si',title:'Assam Police Sub-Inspector (SI)',
    short:'Assam Police SI',icon:'👮',state:'Assam',type:'state',
    category:['police','state'],
    colorBg:'rgba(239,68,68,.15)',colorText:'#f87171',
    conducting:'Assam Police',
    posts:'Sub-Inspector (UB / AB)',
    vacancies:'~500',
    eligibility:'Any Graduate (20-26 yrs)',
    mode:'Online CBT + PST + PET',
    language:'Assamese & English',
    status:'upcoming',
    notification:'Feb 2025',
    applyLast:'March 2025',
    prelims:'June 2025',
    mains:'Aug 2025',
    pst:'Oct 2025',
    pet:'Nov 2025',
    syllabus:{
      'General Knowledge':['History','Geography','Polity','Economy','Science','Current Affairs'],
      'Logical Reasoning':['Reasoning','Mental Ability','Data Interpretation'],
      'Mathematics':['Arithmetic','Algebra','Geometry','Statistics'],
      'English':['Grammar','Vocabulary','Comprehension','Synonyms/Antonyms'],
      'Assamese':['Grammar','Literature','Composition','Translation'],
    },
    pattern:[
      {stage:'Preliminary Exam',papers:'GK 50Q + Reasoning 50Q + Maths 50Q = 150Q',duration:'120 min',marks:'150'},
      {stage:'Main Exam',papers:'GK 40Q + Reasoning 30Q + Maths 30Q + English 50Q + Assamese 50Q = 200Q',duration:'180 min',marks:'200'},
      {stage:'PST (Physical Standard Test)',papers:'Height, Chest, Weight as per category',duration:'—',marks:'Qualifying'},
      {stage:'PET (Physical Efficiency Test)',papers:'Running, Long Jump, High Jump',duration:'As specified',marks:'Qualifying'},
    ],
    cutoffs:[
      {year:'2023',general:'Prelims: 110 / Mains: 160',obc:'105 / 155',sc:'100 / 150',st:'95 / 145',ews:'108 / 158'},
      {year:'2022',general:'115 / 165',obc:'110 / 160',sc:'105 / 155',st:'100 / 150',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'Assam Police SI Guide',type:'Book','desc':'Assam Publications'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── HARYANA ───
  {
    id:'hr_police_constable',title:'Haryana Police Constable',
    short:'Haryana Constable',icon:'👮',state:'Haryana',type:'state',
    category:['police','state','group'],
    colorBg:'rgba(239,68,68,.15)',colorText:'#f87171',
    conducting:'Haryana Staff Selection Commission (HSSC)',
    posts:'Constable (General Duty)',
    vacancies:'~5,000',
    eligibility:'10+2 (18-25 yrs)',
    mode:'Online CBT + PST + PET',
    language:'Hindi & English',
    status:'upcoming',
    notification:'Feb 2025',
    applyLast:'March 2025',
    exam:'June 2025',
    pst:'Aug 2025',
    pet:'Sept 2025',
    syllabus:{
      'General Studies':['History','Geography','Polity','Economy','Science','Current Affairs'],
      'General Science':['Physics','Chemistry','Biology','Computer Science'],
      'Mathematics':['Arithmetic','Algebra','Geometry','Statistics'],
      'General Reasoning':['Logical Reasoning','Mental Ability','Data Interpretation'],
      'Agriculture':['Basic Agriculture','Horticulture','Animal Husbandry'],
      'Animal Husbandry':['Livestock','Poultry','Dairy Farming'],
    },
    pattern:[
      {stage:'Written Exam',papers:'GS 80Q + Science 60Q + Maths 45Q + Reasoning 45Q + Agri/AH 20Q = 250Q',duration:'90 min',marks:'80'},
      {stage:'PST (Physical Standard Test)',papers:'Height, Chest, Weight as per category',duration:'—',marks:'Qualifying'},
      {stage:'PET (Physical Efficiency Test)',papers:'Running, Long Jump, High Jump',duration:'As specified',marks:'Qualifying'},
    ],
    cutoffs:[
      {year:'2023',general:'55',obc:'50',sc:'45',st:'40',ews:'53'},
      {year:'2022',general:'58',obc:'53',sc:'48',st:'43',ews:'56'},
    ],
    materials:[
      {icon:'📖',title:'Haryana Constable Guide',type:'Book','desc':'Haryana Publications'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── HIMACHAL PRADESH ───
  {
    id:'hp_hppsc_hcs',title:'HPPSC Himachal Pradesh Civil Services (HCS)',
    short:'HPPSC HCS',icon:'🏛️',state:'Himachal Pradesh',type:'state',
    category:['state','group'],
    colorBg:'rgba(34,197,94,.15)',colorText:'#22c55e',
    conducting:'Himachal Pradesh Public Service Commission',
    posts:'Deputy Collector, DSP, Assistant Commissioner, etc.',
    vacancies:'~50',
    eligibility:'Any Graduate (21-35 yrs)',
    mode:'Offline (Written)',
    language:'Hindi & English',
    status:'upcoming',
    notification:'Feb 2025',
    applyLast:'March 2025',
    prelims:'June 2025',
    mains:'Sept 2025',
    interview:'Dec 2025',
    syllabus:{
      'General Studies':['Indian History','Geography','Polity','Economy','Science','Current Affairs'],
      'General Studies (CSAT)':['Comprehension','Reasoning','Data Interpretation','Basic Numeracy'],
      'Hindi':['Grammar','Literature','Composition','Translation'],
      'English':['Grammar','Literature','Composition','Translation'],
      'Essay':['Current Topics','Social Issues','Development'],
      'Optional Subject':['Selected by candidate from 27 options'],
    },
    pattern:[
      {stage:'Preliminary (Screening)',papers:'150Q MCQ — General Studies',duration:'120 min',marks:'150'},
      {stage:'Main Exam',papers:'GS I + GS II + Hindi + English + Essay + Optional I + Optional II',duration:'3 hrs each',marks:'1400'},
      {stage:'Interview (Viva-Voce)',papers:'Personality Assessment',duration:'—',marks:'150'},
    ],
    cutoffs:[
      {year:'2023',general:'Prelims: 100 / Mains: 650',obc:'95 / 625',sc:'90 / 600',st:'85 / 575',ews:'98 / 640'},
      {year:'2022',general:'97 / 630',obc:'92 / 605',sc:'87 / 580',st:'82 / 555',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'HPPSC HCS Guide',type:'Book','desc':'Himachal Publications'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── UTTARAKHAND ───
  {
    id:'uk_ukpsc_acs',title:'UKPSC Uttarakhand Civil Services (ACS)',
    short:'UKPSC ACS',icon:'🏛️',state:'Uttarakhand',type:'state',
    category:['state','group'],
    colorBg:'rgba(16,185,129,.15)',colorText:'#34d399',
    conducting:'Uttarakhand Public Service Commission',
    posts:'Deputy Collector, DSP, Assistant Commissioner, etc.',
    vacancies:'~80',
    eligibility:'Any Graduate (21-35 yrs)',
    mode:'Offline (Written)',
    language:'Hindi & English',
    status:'upcoming',
    notification:'Feb 2025',
    applyLast:'March 2025',
    prelims:'June 2025',
    mains:'Sept 2025',
    interview:'Dec 2025',
    syllabus:{
      'General Studies':['Indian History','Geography','Polity','Economy','Science','Current Affairs'],
      'General Studies (CSAT)':['Comprehension','Reasoning','Data Interpretation','Basic Numeracy'],
      'Hindi':['Grammar','Literature','Composition','Translation'],
      'English':['Grammar','Literature','Composition','Translation'],
      'Essay':['Current Topics','Social Issues','Development'],
      'Optional Subject':['Selected by candidate from 29 options'],
    },
    pattern:[
      {stage:'Preliminary (Screening)',papers:'150Q MCQ — General Studies',duration:'120 min',marks:'150'},
      {stage:'Main Exam',papers:'GS I + GS II + Hindi + English + Essay + Optional I + Optional II',duration:'3 hrs each',marks:'1400'},
      {stage:'Interview (Viva-Voce)',papers:'Personality Assessment',duration:'—',marks:'150'},
    ],
    cutoffs:[
      {year:'2023',general:'Prelims: 95 / Mains: 620',obc:'90 / 595',sc:'85 / 570',st:'80 / 545',ews:'93 / 615'},
      {year:'2022',general:'92 / 600',obc:'87 / 575',sc:'82 / 550',st:'77 / 525',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'UKPSC ACS Guide',type:'Book','desc':'Uttarakhand Publications'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── CHHATTISGARH ───
  {
    id:'cg_cgpsc_state',title:'CGPSC State Service Exam',
    short:'CGPSC State',icon:'🏛️',state:'Chhattisgarh',type:'state',
    category:['state','group'],
    colorBg:'rgba(168,85,247,.15)',colorText:'#a855f7',
    conducting:'Chhattisgarh Public Service Commission',
    posts:'Deputy Collector, DSP, Assistant Commissioner, etc.',
    vacancies:'~100',
    eligibility:'Any Graduate (21-35 yrs)',
    mode:'Offline (Written)',
    language:'Hindi & English',
    status:'upcoming',
    notification:'Feb 2025',
    applyLast:'March 2025',
    prelims:'June 2025',
    mains:'Sept 2025',
    interview:'Dec 2025',
    syllabus:{
      'General Studies':['Indian History','Geography','Polity','Economy','Science','Current Affairs'],
      'General Studies (CSAT)':['Comprehension','Reasoning','Data Interpretation','Basic Numeracy'],
      'Chhattisgarhi Language':['Grammar','Literature','Composition','Translation'],
      'English':['Grammar','Literature','Composition','Translation'],
      'Essay':['Current Topics','Social Issues','Development'],
      'Optional Subject':['Selected by candidate from 25 options'],
    },
    pattern:[
      {stage:'Preliminary (Screening)',papers:'150Q MCQ — General Studies',duration:'120 min',marks:'150'},
      {stage:'Main Exam',papers:'GS I + GS II + Chhattisgarhi + English + Essay + Optional I + Optional II',duration:'3 hrs each',marks:'1400'},
      {stage:'Interview (Viva-Voce)',papers:'Personality Assessment',duration:'—',marks:'150'},
    ],
    cutoffs:[
      {year:'2023',general:'Prelims: 90 / Mains: 600',obc:'85 / 575',sc:'80 / 550',st:'75 / 525',ews:'88 / 590'},
      {year:'2022',general:'87 / 580',obc:'82 / 555',sc:'77 / 530',st:'72 / 505',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'CGPSC State Guide',type:'Book','desc':'Chhattisgarh Publications'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── DEFENCE ───
  {
    id:'cds',title:'Combined Defence Services (CDS) Exam',
    short:'CDS',icon:'⚔️',state:'Central',type:'central',
    category:['defence','central'],
    colorBg:'rgba(239,68,68,.15)',colorText:'#f87171',
    conducting:'Union Public Service Commission',
    posts:'IMA, INA, AFA, OTA — Permanent Commission',
    vacancies:'~400 (IMA/INA/AFA) + 200 (OTA)',
    eligibility:'Graduate (19-24 yrs for IMA/INA/AFA, 19-25 for OTA)',
    mode:'Offline (Written) + SSB',
    language:'English & Hindi',
    status:'active',
    notification:'Dec 2024 (I) / May 2025 (II)',
    applyLast:'Jan 2025 / June 2025',
    written:'April 2025 / Sept 2025',
    ssb:'June–Sept 2025',
    result:'Dec 2025',
    syllabus:{
      'English':['Grammar','Vocabulary','Comprehension','Synonyms/Antonyms'],
      'General Knowledge':['History','Geography','Polity','Economy','Science','Current Affairs'],
      'Elementary Mathematics':['Arithmetic','Algebra','Geometry','Trigonometry','Statistics'],
    },
    pattern:[
      {stage:'Written — English',papers:'120 Questions',duration:'2 hrs',marks:'100'},
      {stage:'Written — GK',papers:'120 Questions',duration:'2 hrs',marks:'100'},
      {stage:'Written — Maths',papers:'100 Questions',duration:'2 hrs',marks:'100'},
      {stage:'SSB Interview',papers:'Psychological Tests + GTO + Interview + Conference',duration:'5 days',marks:'300'},
    ],
    cutoffs:[
      {year:'2023 I',general:'(Written) 120 / (Final) 240',obc:'—',sc:'—',st:'—',ews:'—'},
      {year:'2022 II',general:'115 / 235',obc:'—',sc:'—',st:'—',ews:'—'},
    ],
    materials:[
      {icon:'📖',title:'Pathfinder CDS',type:'Book','desc':'Arihant'},
      {icon:'📋',title:'Previous 10 Years',type:'PDF','desc':'Solved papers'},
      {icon:'🎥',title:'SSB Crack',type:'YouTube','desc':'Free videos'},
    ],
  },

  // ─── TEACHING ───
  {
    id:'ctet',title:'Central Teacher Eligibility Test (CTET)',
    short:'CTET',icon:'📚',state:'Central',type:'central',
    category:['teacher','central'],
    colorBg:'rgba(34,197,94,.15)',colorText:'#22c55e',
    conducting:'Central Board of Secondary Education (CBSE)',
    posts:'Primary Teacher (Class I-V) / Elementary Teacher (Class VI-VIII)',
    vacancies:'Qualifying certificate for teaching jobs',
    eligibility:'12th Pass for Primary, Graduate for Elementary + B.Ed/D.El.Ed',
    mode:'Online CBT',
    language:'15 languages',
    status:'active',
    notification:'Dec 2024 (Dec) / June 2025 (July)',
    applyLast:'Jan 2025 / July 2025',
    exam:'Feb 2025 / Aug 2025',
    result:'April 2025 / Oct 2025',
    syllabus:{
      'Child Development & Pedagogy':['Child Psychology','Learning Theories','Teaching Methods','Assessment'],
      'Language I (Compulsory)':['Grammar','Comprehension','Pedagogy of Language Development'],
      'Language II (Compulsory)':['Grammar','Comprehension','Pedagogy of Language Development'],
      'Mathematics':['Numbers','Geometry','Data Handling','Pedagogical Issues'],
      'Environmental Studies':['Family','Food','Shelter','Water','Travel','Things We Make','Pedagogical Issues'],
    },
    pattern:[
      {stage:'Paper I (Primary)',papers:'Child Development 30Q + Language I 30Q + Language II 30Q + Maths 30Q + EVS 30Q = 150Q',duration:'150 min',marks:'150'},
      {stage:'Paper II (Elementary)',papers:'Child Development 30Q + Language I 30Q + Language II 30Q + Maths/Science/Social Science 60Q = 150Q',duration:'150 min',marks:'150'},
    ],
    cutoffs:[
      {year:'2023 Dec',general:'90 (Paper I) / 90 (Paper II)',obc:'—',sc:'—',st:'—',ews:'—'},
      {year:'2022 July',general:'87 / 88',obc:'—',sc:'—',st:'—',ews:'—'},
    ],
    materials:[
      {icon:'📖',title:'CTET Guide',type:'Book','desc':'Arihant / Pearson'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
      {icon:'🎥',title:'CTET Adda YouTube',type:'Free','desc':'Free classes'},
    ],
  },

  // ─── MEDICAL ───
  {
    id:'neet',title:'National Eligibility cum Entrance Test (NEET) UG',
    short:'NEET UG',icon:'🏥',state:'Central',type:'central',
    category:['medical','central'],
    colorBg:'rgba(239,68,68,.15)',colorText:'#f87171',
    conducting:'National Testing Agency (NTA)',
    posts:'MBBS, BDS, BAMS, BHMS, BUMS, BSMS, BNYS courses',
    vacancies:'~1,00,000 seats across medical colleges',
    eligibility:'12th Science (PCB) with 50% marks (40% for reserved)',
    mode:'Offline (OMR)',
    language:'13 languages',
    status:'active',
    notification:'Dec 2024 (Phase 1) / Feb 2025 (Phase 2)',
    applyLast:'Jan 2025 / March 2025',
    exam:'May 2025',
    result:'June 2025',
    syllabus:{
      'Physics':['Class 11: Physical World, Units, Motion, Laws of Motion, Work/Energy/Power, Systems of Particles, Gravitation, Thermodynamics, Kinetic Theory, Oscillations, Waves','Class 12: Electrostatics, Current Electricity, Magnetic Effects, Magnetism, EMI, AC, EM Waves, Optics, Dual Nature, Atoms, Nuclei, Semiconductor'],
      'Chemistry':['Class 11: Basic Concepts, Structure of Atom, Classification, Chemical Bonding, States of Matter, Thermodynamics, Equilibrium, Redox, Hydrogen, s-Block, p-Block, Organic Chemistry','Class 12: Solid State, Solutions, Electrochemistry, Chemical Kinetics, Surface Chemistry, p-Block, d-Block, Coordination, Haloalkanes, Alcohols, Phenols, Ethers, Aldehydes, Ketones, Carboxylic Acids, Amines, Biomolecules, Polymers, Chemistry in Everyday Life'],
      'Biology':['Class 11: Diversity in Living World, Structural Organisation, Cell Structure, Plant Physiology, Human Physiology','Class 12: Reproduction, Genetics, Biology in Human Welfare, Biotechnology, Ecology'],
    },
    pattern:[
      {stage:'Single Paper',papers:'Physics 45Q + Chemistry 45Q + Biology 90Q = 180Q',duration:'200 min',marks:'720'},
    ],
    cutoffs:[
      {year:'2023',general:'720-137 (Varies by college)',obc:'136-107',sc:'136-107',st:'136-107',ews:'136-107'},
      {year:'2022',general:'715-117',obc:'116-93',sc:'116-93',st:'116-93',ews:'116-93'},
    ],
    materials:[
      {icon:'📖',title:'NCERT Books',type:'Free','desc':'Class 11 & 12'},
      {icon:'📋',title:'NEET Previous Papers',type:'PDF','desc':'All years'},
      {icon:'🎥',title:'NEET Adda YouTube',type:'Free','desc':'Free classes'},
      {icon:'📱',title:'NEET App',type:'App','desc':'Mock tests'},
    ],
  },

  // ─── AGRICULTURE ───
  {
    id:'icar_aieea',title:'ICAR AIEEA UG',
    short:'ICAR AIEEA UG',icon:'🌾',state:'Central',type:'central',
    category:['agriculture','central'],
    colorBg:'rgba(34,197,94,.15)',colorText:'#22c55e',
    conducting:'Indian Council of Agricultural Research (ICAR)',
    posts:'BSc Agriculture, Horticulture, Forestry, Fisheries, etc.',
    vacancies:'~15,000 seats across agricultural universities',
    eligibility:'12th Science (PCM/PCB) with 50% marks',
    mode:'Online CBT',
    language:'English & Hindi',
    status:'active',
    notification:'Dec 2024',
    applyLast:'Jan 2025',
    exam:'April 2025',
    result:'May 2025',
    syllabus:{
      'Physics':['Mechanics','Electricity','Magnetism','Optics','Modern Physics'],
      'Chemistry':['Physical Chemistry','Organic Chemistry','Inorganic Chemistry'],
      'Biology/Agriculture':['Botany','Zoology','Agriculture','Horticulture','Animal Husbandry'],
      'Mathematics':['Algebra','Calculus','Coordinate Geometry','Trigonometry'],
    },
    pattern:[
      {stage:'Single Paper',papers:'Physics 60Q + Chemistry 60Q + Biology/Agri 60Q + Maths 60Q = 240Q',duration:'150 min',marks:'600'},
    ],
    cutoffs:[
      {year:'2023',general:'200-250 (Varies by course)',obc:'180-230',sc:'160-210',st:'150-200',ews:'190-240'},
      {year:'2022',general:'190-240',obc:'170-220',sc:'150-200',st:'140-190',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'ICAR Guide',type:'Book','desc':'Arihant'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── FOREST ───
  {
    id:'ifos',title:'Indian Forest Service (IFoS) Exam',
    short:'IFoS',icon:'🌲',state:'Central',type:'central',
    category:['forest','central'],
    conducting:'Union Public Service Commission',
    posts:'Indian Forest Service Officers',
    vacancies:'~150',
    eligibility:'Any Graduate with Science subjects',
    mode:'Offline (Written) + Interview',
    language:'English & Hindi',
    status:'upcoming',
    notification:'Feb 2025',
    applyLast:'March 2025',
    prelims:'June 2025',
    mains:'Sept 2025',
    interview:'Jan 2026',
    result:'April 2026',
    syllabus:{
      'General English':['Essay','Precis','Comprehension','Grammar'],
      'General Knowledge':['Current Events','History','Geography','Polity','Economy','Science'],
      'General Studies':['Indian Polity','Governance','Constitution','Public Policy','Rights Issues','Development'],
      'Optional Subject I':['Selected by candidate from 25 options'],
      'Optional Subject II':['Selected by candidate from 25 options'],
    },
    pattern:[
      {stage:'Preliminary (Screening)',papers:'GS Paper I 100Q + CSAT 80Q',duration:'2 hrs each',marks:'200+200'},
      {stage:'Main Exam',papers:'General English + GK + GS + Optional I + Optional II',duration:'3 hrs each',marks:'1400'},
      {stage:'Interview (Viva-Voce)',papers:'Personality Assessment',duration:'—',marks:'300'},
    ],
    cutoffs:[
      {year:'2023',general:'1009 (Combined with IAS)',obc:'994',sc:'981',st:'958',ews:'984'},
      {year:'2022',general:'1011',obc:'999',sc:'988',st:'960',ews:'987'},
    ],
    materials:[
      {icon:'📖',title:'IFoS Guide',type:'Book','desc':'Unique Publications'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },

  // ─── REVENUE ───
  {
    id:'ssc_cpo',title:'SSC Central Police Organization (CPO)',
    short:'SSC CPO',icon:'👮',state:'Central',type:'central',
    category:['police','central','revenue'],
    colorBg:'rgba(239,68,68,.15)',colorText:'#f87171',
    conducting:'Staff Selection Commission',
    posts:'SI in Delhi Police, CAPF, CISF, etc.',
    vacancies:'~2,000',
    eligibility:'Any Graduate (20-25 yrs)',
    mode:'Online CBT + PST + PET + Medical',
    language:'English & Hindi',
    status:'upcoming',
    notification:'March 2025',
    applyLast:'April 2025',
    tier1:'July 2025',
    tier2:'Sept 2025',
    pst:'Nov 2025',
    pet:'Dec 2025',
    syllabus:{
      'General Intelligence & Reasoning':['Analogies','Coding-Decoding','Blood Relations','Series','Puzzles','Non-verbal'],
      'General Knowledge':['History','Geography','Polity','Economy','Science','Current Affairs'],
      'Quantitative Aptitude':['Number System','Ratio & Proportion','Percentage','Profit-Loss','Geometry','Trigonometry','DI'],
      'English Comprehension':['Reading Comprehension','Error Spotting','Fill in Blanks','One Word Sub','Cloze Test'],
    },
    pattern:[
      {stage:'Paper I (Tier I)',papers:'GI&R 50Q + GK 50Q + Quant 50Q + Eng 50Q = 200Q',duration:'120 min',marks:'200'},
      {stage:'Paper II (Tier II)',papers:'English Language & Comprehension 200Q',duration:'120 min',marks:'200'},
      {stage:'PST (Physical Standard Test)',papers:'Height, Chest, Weight as per category',duration:'—',marks:'Qualifying'},
      {stage:'PET (Physical Efficiency Test)',papers:'Running, Long Jump, High Jump',duration:'As specified',marks:'Qualifying'},
    ],
    cutoffs:[
      {year:'2023',general:'Tier I: 130 / Tier II: 160',obc:'125 / 155',sc:'120 / 150',st:'115 / 145',ews:'128 / 158'},
      {year:'2022',general:'135 / 165',obc:'130 / 160',sc:'125 / 155',st:'120 / 150',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'SSC CPO Guide',type:'Book','desc':'Arihant / Kiran'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
      {icon:'🎥',title:'SSC Adda YouTube',type:'Free','desc':'Video lectures'},
    ],
  },

  // ─── JUDICIAL ───
  {
    id:'clat',title:'Common Law Admission Test (CLAT)',
    short:'CLAT',icon:'⚖️',state:'Central',type:'central',
    category:['judicial','central'],
    colorBg:'rgba(168,85,247,.15)',colorText:'#a855f7',
    conducting:'Consortium of National Law Universities',
    posts:'Admission to 22 NLUs for 5-year LLB program',
    vacancies:'~3,000 seats across NLUs',
    eligibility:'12th Pass with 45% marks (40% for reserved)',
    mode:'Online CBT',
    language:'English',
    status:'active',
    notification:'Dec 2024',
    applyLast:'Jan 2025',
    exam:'May 2025',
    result:'June 2025',
    syllabus:{
      'English Language':['Comprehension','Grammar','Vocabulary','Synonyms/Antonyms','Idioms'],
      'Current Affairs & GK':['National & International Events','Awards','Sports','Science','History','Geography','Polity'],
      'Legal Reasoning':['Legal Principles','Facts','Conclusions','Legal Maxims','Torts','Contracts','Criminal Law'],
      'Logical Reasoning':['Analogies','Series','Coding-Decoding','Blood Relations','Directions','Syllogism'],
      'Quantitative Techniques':['Basic Mathematics','Ratios','Percentages','Profit-Loss','Time-Speed-Distance'],
    },
    pattern:[
      {stage:'Single Paper',papers:'English 28-32Q + GK 35-39Q + Legal 35-39Q + Logical 28-32Q + Quant 13-17Q = 150Q',duration:'120 min',marks:'150'},
    ],
    cutoffs:[
      {year:'2023',general:'85-95 (Varies by NLU)',obc:'75-85',sc:'70-80',st:'65-75',ews:'80-90'},
      {year:'2022',general:'80-90',obc:'70-80',sc:'65-75',st:'60-70',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'CLAT Guide',type:'Book','desc':'Pearson / Universal'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
      {icon:'🎥',title:'CLAT Adda YouTube',type:'Free','desc':'Free classes'},
    ],
  },

  // ─── ENGINEERING ───
  {
    id:'jeemain',title:'JEE Main',
    short:'JEE Main',icon:'⚙️',state:'Central',type:'central',
    category:['engineering','central'],
    colorBg:'rgba(59,130,246,.15)',colorText:'#60a5fa',
    conducting:'National Testing Agency (NTA)',
    posts:'Admission to NITs, IIITs, CFTIs for B.Tech/B.Arch/B.Planning',
    vacancies:'~25,000 seats in NITs + IIITs + CFTIs',
    eligibility:'12th Science (PCM) with 75% marks (65% for reserved)',
    mode:'Online CBT',
    language:'13 languages',
    status:'active',
    notification:'Nov 2024 (Jan Session) / Feb 2025 (April Session)',
    applyLast:'Dec 2024 / March 2025',
    exam:'Jan–Feb 2025 / April 2025',
    result:'Feb–March 2025 / April 2025',
    syllabus:{
      'Physics':['Mechanics','Electricity & Magnetism','Optics','Modern Physics','Thermodynamics','Waves','Electrostatics'],
      'Chemistry':['Physical Chemistry','Organic Chemistry','Inorganic Chemistry','Coordination Compounds','p-Block','d-Block'],
      'Mathematics':['Algebra','Calculus','Coordinate Geometry','Trigonometry','Vectors','3D Geometry','Statistics'],
    },
    pattern:[
      {stage:'Paper 1 (B.Tech)',papers:'Physics 20Q + Chemistry 20Q + Maths 20Q = 60Q (MCQ) + 10 Numerical',duration:'180 min',marks:'300'},
      {stage:'Paper 2A (B.Arch)',papers:'Maths 20Q + Aptitude 50Q + Drawing 2Q = 72Q',duration:'180 min',marks:'400'},
      {stage:'Paper 2B (B.Planning)',papers:'Maths 20Q + Aptitude 50Q + Planning 25Q = 95Q',duration:'180 min',marks:'400'},
    ],
    cutoffs:[
      {year:'2023 Jan',general:'90-95 percentile (Varies by institute)',obc:'70-80',sc:'50-60',st:'40-50',ews:'80-85'},
      {year:'2022 April',general:'88-93',obc:'68-78',sc:'48-58',st:'38-48',ews:'N/A'},
    ],
    materials:[
      {icon:'📖',title:'NCERT Books',type:'Free','desc':'Class 11 & 12'},
      {icon:'📋',title:'JEE Previous Papers',type:'PDF','desc':'All years'},
      {icon:'🎥',title:'JEE Adda YouTube',type:'Free','desc':'Free classes'},
      {icon:'📱',title:'JEE App',type:'App','desc':'Mock tests'},
    ],
  },

  // ─── GROUP D ───
  {
    id:'cg_groupd',title:'CG Police Constable (Group D)',
    short:'CG Constable',icon:'👮',state:'Chhattisgarh',type:'state',
    category:['police','state','group'],
    colorBg:'rgba(239,68,68,.15)',colorText:'#f87171',
    conducting:'Chhattisgarh Police',
    posts:'Constable (General Duty)',
    vacancies:'~2,000',
    eligibility:'10th Pass (18-25 yrs)',
    mode:'Online CBT + PST + PET',
    language:'Hindi & English',
    status:'upcoming',
    notification:'Feb 2025',
    applyLast:'March 2025',
    exam:'June 2025',
    pst:'Aug 2025',
    pet:'Sept 2025',
    syllabus:{
      'General Knowledge':['History','Geography','Polity','Economy','Science','Current Affairs'],
      'General Hindi':['Grammar','Vocabulary','Comprehension','Synonyms/Antonyms'],
      'Mathematics':['Arithmetic','Algebra','Geometry','Statistics'],
      'Reasoning':['Logical Reasoning','Mental Ability','Data Interpretation'],
    },
    pattern:[
      {stage:'Written Exam',papers:'GK 40Q + Hindi 30Q + Maths 30Q + Reasoning 30Q = 130Q',duration:'120 min',marks:'130'},
      {stage:'PST (Physical Standard Test)',papers:'Height, Chest, Weight as per category',duration:'—',marks:'Qualifying'},
      {stage:'PET (Physical Efficiency Test)',papers:'Running, Long Jump, High Jump',duration:'As specified',marks:'Qualifying'},
    ],
    cutoffs:[
      {year:'2023',general:'75',obc:'70',sc:'65',st:'60',ews:'73'},
      {year:'2022',general:'78',obc:'73',sc:'68',st:'63',ews:'76'},
    ],
    materials:[
      {icon:'📖',title:'CG Constable Guide',type:'Book','desc':'CG Publications'},
      {icon:'📋',title:'Previous Papers',type:'PDF','desc':'All years'},
    ],
  },
];